name: Delete unused packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete untagged platform-plugin-dev packages
        uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: platform-plugin-dev

      - name: Delete untagged platform-plugin-dev-base packages
        uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: platform-plugin-dev-base