name: Delete unused packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Delete untagged platform-plugin-dev packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: platform-plugin-dev
          delete-only-untagged-versions: "true"

      - name: Delete untagged platform-plugin-dev-base packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: platform-plugin-dev-base
          delete-only-untagged-versions: "true"