name: Delete unused packages

on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete untagged platform-plugin-dev-base packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: platform-plugin-dev-base
          package-type: container
          token: ${{ secrets.PAT_TOKEN_GITHUB }}
          min-versions-to-keep: 0
          delete-only-untagged-versions: "true"

      - name: Delete untagged platform-plugin-dev packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: platform-plugin-dev
          package-type: container
          token: ${{ secrets.PAT_TOKEN_GITHUB }}
          min-versions-to-keep: 0
          delete-only-untagged-versions: "true"
